# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASzvhDgyPj_xFFiVRqm0qn0rwcnrthwk
"""

print("hi")